name: Build and Publish image to Docker Hub 

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image 
        run: docker build . -t dcorr25/fast-api-backend:latest

      - name: Login to Dcoker Hub 
        uses: docker/login-action@v3
        with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image to docker hub
        run: docker push dcorr25/fast-api-backend:latest
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy FastAPI container" \
            --parameters commands='[
              "sudo docker pull dcorr25/fast-api-backend:latest",
              "sudo docker stop fast-api || true",
              "sudo docker rm fast-api || true",
              "sudo docker run -d --name fast-api -p 8000:8000 dcorr25/fast-api-backend:latest"
            ]' \
            --region eu-west-1
        
      
